// Question seed data for all subjects
// Each question has text in 3 languages, 4 options, and correct answer index (0-3)

interface QuestionSeed {
  subject: string;
  questionTextRu: string;
  questionTextKz: string;
  questionTextEn: string;
  optionsRu: string[];
  optionsKz: string[];
  optionsEn: string[];
  correctAnswer: number;
  difficulty: string;
  topic: string;
}

export const questionSeeds: QuestionSeed[] = [
  // MATH LITERACY (15+ questions)
  {
    subject: "math_literacy",
    questionTextRu: "Чему равно 15% от 200?",
    questionTextKz: "200-дің 15%-ы нешеге тең?",
    questionTextEn: "What is 15% of 200?",
    optionsRu: ["25", "30", "35", "20"],
    optionsKz: ["25", "30", "35", "20"],
    optionsEn: ["25", "30", "35", "20"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Проценты",
  },
  {
    subject: "math_literacy",
    questionTextRu: "Решите уравнение: 2x + 5 = 15",
    questionTextKz: "Теңдеуді шешіңіз: 2x + 5 = 15",
    questionTextEn: "Solve the equation: 2x + 5 = 15",
    optionsRu: ["3", "5", "7", "10"],
    optionsKz: ["3", "5", "7", "10"],
    optionsEn: ["3", "5", "7", "10"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Уравнения",
  },
  {
    subject: "math_literacy",
    questionTextRu: "Площадь прямоугольника со сторонами 6 и 8 равна:",
    questionTextKz: "Қабырғалары 6 және 8 тікбұрыштың ауданы:",
    questionTextEn: "The area of a rectangle with sides 6 and 8 is:",
    optionsRu: ["14", "48", "28", "36"],
    optionsKz: ["14", "48", "28", "36"],
    optionsEn: ["14", "48", "28", "36"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Геометрия",
  },
  {
    subject: "math_literacy",
    questionTextRu: "Какое число является простым?",
    questionTextKz: "Қай сан жай сан болып табылады?",
    questionTextEn: "Which number is prime?",
    optionsRu: ["4", "9", "17", "15"],
    optionsKz: ["4", "9", "17", "15"],
    optionsEn: ["4", "9", "17", "15"],
    correctAnswer: 2,
    difficulty: "easy",
    topic: "Теория чисел",
  },
  {
    subject: "math_literacy",
    questionTextRu: "Найдите значение выражения: √144",
    questionTextKz: "Өрнектің мәнін табыңыз: √144",
    questionTextEn: "Find the value: √144",
    optionsRu: ["10", "11", "12", "14"],
    optionsKz: ["10", "11", "12", "14"],
    optionsEn: ["10", "11", "12", "14"],
    correctAnswer: 2,
    difficulty: "easy",
    topic: "Арифметика",
  },
  {
    subject: "math_literacy",
    questionTextRu: "Товар стоил 5000 тг. После скидки 20% его цена составит:",
    questionTextKz: "Тауар 5000 тг тұрды. 20% жеңілдіктен кейін бағасы:",
    questionTextEn: "An item cost 5000 tg. After a 20% discount its price is:",
    optionsRu: ["3000 тг", "3500 тг", "4000 тг", "4500 тг"],
    optionsKz: ["3000 тг", "3500 тг", "4000 тг", "4500 тг"],
    optionsEn: ["3000 tg", "3500 tg", "4000 tg", "4500 tg"],
    correctAnswer: 2,
    difficulty: "medium",
    topic: "Проценты",
  },
  {
    subject: "math_literacy",
    questionTextRu: "Среднее арифметическое чисел 4, 8, 12 равно:",
    questionTextKz: "4, 8, 12 сандарының арифметикалық ортасы:",
    questionTextEn: "The arithmetic mean of 4, 8, 12 is:",
    optionsRu: ["6", "7", "8", "9"],
    optionsKz: ["6", "7", "8", "9"],
    optionsEn: ["6", "7", "8", "9"],
    correctAnswer: 2,
    difficulty: "easy",
    topic: "Статистика",
  },
  {
    subject: "math_literacy",
    questionTextRu: "Если a = 3, b = 4, то a² + b² равно:",
    questionTextKz: "Егер a = 3, b = 4 болса, a² + b² тең:",
    questionTextEn: "If a = 3, b = 4, then a² + b² equals:",
    optionsRu: ["7", "12", "25", "49"],
    optionsKz: ["7", "12", "25", "49"],
    optionsEn: ["7", "12", "25", "49"],
    correctAnswer: 2,
    difficulty: "easy",
    topic: "Алгебра",
  },
  {
    subject: "math_literacy",
    questionTextRu: "Периметр квадрата со стороной 5 см равен:",
    questionTextKz: "Қабырғасы 5 см шаршының периметрі:",
    questionTextEn: "The perimeter of a square with side 5 cm is:",
    optionsRu: ["10 см", "15 см", "20 см", "25 см"],
    optionsKz: ["10 см", "15 см", "20 см", "25 см"],
    optionsEn: ["10 cm", "15 cm", "20 cm", "25 cm"],
    correctAnswer: 2,
    difficulty: "easy",
    topic: "Геометрия",
  },
  {
    subject: "math_literacy",
    questionTextRu: "Сколько минут в 2.5 часах?",
    questionTextKz: "2.5 сағатта неше минут бар?",
    questionTextEn: "How many minutes in 2.5 hours?",
    optionsRu: ["120", "130", "150", "160"],
    optionsKz: ["120", "130", "150", "160"],
    optionsEn: ["120", "130", "150", "160"],
    correctAnswer: 2,
    difficulty: "easy",
    topic: "Единицы измерения",
  },
  {
    subject: "math_literacy",
    questionTextRu: "НОК чисел 6 и 8 равен:",
    questionTextKz: "6 және 8 сандарының ЕОБ-ы:",
    questionTextEn: "LCM of 6 and 8 is:",
    optionsRu: ["12", "16", "24", "48"],
    optionsKz: ["12", "16", "24", "48"],
    optionsEn: ["12", "16", "24", "48"],
    correctAnswer: 2,
    difficulty: "medium",
    topic: "Теория чисел",
  },
  {
    subject: "math_literacy",
    questionTextRu: "Дробь 3/4 в процентах равна:",
    questionTextKz: "3/4 бөлшегі пайызбен:",
    questionTextEn: "The fraction 3/4 as a percentage is:",
    optionsRu: ["25%", "50%", "75%", "80%"],
    optionsKz: ["25%", "50%", "75%", "80%"],
    optionsEn: ["25%", "50%", "75%", "80%"],
    correctAnswer: 2,
    difficulty: "easy",
    topic: "Дроби",
  },
  {
    subject: "math_literacy",
    questionTextRu: "Решите неравенство: 3x > 12",
    questionTextKz: "Теңсіздікті шешіңіз: 3x > 12",
    questionTextEn: "Solve the inequality: 3x > 12",
    optionsRu: ["x > 3", "x > 4", "x > 6", "x > 9"],
    optionsKz: ["x > 3", "x > 4", "x > 6", "x > 9"],
    optionsEn: ["x > 3", "x > 4", "x > 6", "x > 9"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Неравенства",
  },
  {
    subject: "math_literacy",
    questionTextRu: "Объем куба с ребром 3 см равен:",
    questionTextKz: "Қыры 3 см куб көлемі:",
    questionTextEn: "The volume of a cube with edge 3 cm is:",
    optionsRu: ["9 см³", "18 см³", "27 см³", "36 см³"],
    optionsKz: ["9 см³", "18 см³", "27 см³", "36 см³"],
    optionsEn: ["9 cm³", "18 cm³", "27 cm³", "36 cm³"],
    correctAnswer: 2,
    difficulty: "medium",
    topic: "Геометрия",
  },
  {
    subject: "math_literacy",
    questionTextRu: "Скорость автомобиля 60 км/ч. За 2.5 часа он проедет:",
    questionTextKz: "Автокөліктің жылдамдығы 60 км/сағ. 2.5 сағатта ол жүреді:",
    questionTextEn: "Car speed is 60 km/h. In 2.5 hours it will travel:",
    optionsRu: ["120 км", "130 км", "150 км", "180 км"],
    optionsKz: ["120 км", "130 км", "150 км", "180 км"],
    optionsEn: ["120 km", "130 km", "150 km", "180 km"],
    correctAnswer: 2,
    difficulty: "easy",
    topic: "Задачи на движение",
  },

  // READING LITERACY (15+ questions)
  {
    subject: "reading_literacy",
    questionTextRu: "Синоним слова 'большой':",
    questionTextKz: "'Үлкен' сөзінің синонимі:",
    questionTextEn: "A synonym for 'big':",
    optionsRu: ["маленький", "огромный", "быстрый", "тихий"],
    optionsKz: ["кішкентай", "зор", "жылдам", "тыныш"],
    optionsEn: ["small", "enormous", "fast", "quiet"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Лексика",
  },
  {
    subject: "reading_literacy",
    questionTextRu: "Антоним слова 'горячий':",
    questionTextKz: "'Ыстық' сөзінің антонимі:",
    questionTextEn: "An antonym of 'hot':",
    optionsRu: ["теплый", "холодный", "жаркий", "прохладный"],
    optionsKz: ["жылы", "суық", "ыстық", "салқын"],
    optionsEn: ["warm", "cold", "burning", "cool"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Лексика",
  },
  {
    subject: "reading_literacy",
    questionTextRu: "Какой жанр литературы описывает реальные события?",
    questionTextKz: "Әдебиеттің қай жанры нақты оқиғаларды сипаттайды?",
    questionTextEn: "Which literary genre describes real events?",
    optionsRu: ["Фантастика", "Документальная проза", "Сказка", "Фэнтези"],
    optionsKz: ["Фантастика", "Деректі проза", "Ертегі", "Фэнтези"],
    optionsEn: ["Science fiction", "Non-fiction", "Fairy tale", "Fantasy"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Жанры",
  },
  {
    subject: "reading_literacy",
    questionTextRu: "Что такое метафора?",
    questionTextKz: "Метафора дегеніміз не?",
    questionTextEn: "What is a metaphor?",
    optionsRu: [
      "Прямое сравнение",
      "Скрытое сравнение",
      "Преувеличение",
      "Противопоставление",
    ],
    optionsKz: [
      "Тура салыстыру",
      "Жасырын салыстыру",
      "Асыра сілтеу",
      "Қарсы қою",
    ],
    optionsEn: [
      "Direct comparison",
      "Hidden comparison",
      "Exaggeration",
      "Contrast",
    ],
    correctAnswer: 1,
    difficulty: "medium",
    topic: "Художественные средства",
  },
  {
    subject: "reading_literacy",
    questionTextRu: "Главная мысль текста — это:",
    questionTextKz: "Мәтіннің негізгі ойы — бұл:",
    questionTextEn: "The main idea of a text is:",
    optionsRu: [
      "Первое предложение",
      "Ключевая идея автора",
      "Последний абзац",
      "Заголовок",
    ],
    optionsKz: [
      "Бірінші сөйлем",
      "Автордың негізгі идеясы",
      "Соңғы абзац",
      "Тақырып",
    ],
    optionsEn: [
      "The first sentence",
      "The author's key idea",
      "The last paragraph",
      "The title",
    ],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Анализ текста",
  },
  {
    subject: "reading_literacy",
    questionTextRu: "Какой знак препинания ставится в конце вопросительного предложения?",
    questionTextKz: "Сұраулы сөйлемнің соңына қандай тыныс белгісі қойылады?",
    questionTextEn: "What punctuation mark is placed at the end of a question?",
    optionsRu: ["Точка", "Вопросительный знак", "Восклицательный знак", "Запятая"],
    optionsKz: ["Нүкте", "Сұрау белгісі", "Леп белгісі", "Үтір"],
    optionsEn: ["Period", "Question mark", "Exclamation mark", "Comma"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Пунктуация",
  },
  {
    subject: "reading_literacy",
    questionTextRu: "Эпитет — это:",
    questionTextKz: "Эпитет — бұл:",
    questionTextEn: "An epithet is:",
    optionsRu: [
      "Преувеличение",
      "Образное определение",
      "Повторение слов",
      "Противопоставление",
    ],
    optionsKz: [
      "Асыра сілтеу",
      "Бейнелі анықтама",
      "Сөздерді қайталау",
      "Қарсы қою",
    ],
    optionsEn: [
      "Exaggeration",
      "Figurative definition",
      "Repetition of words",
      "Contrast",
    ],
    correctAnswer: 1,
    difficulty: "medium",
    topic: "Художественные средства",
  },
  {
    subject: "reading_literacy",
    questionTextRu: "Сколько падежей в русском языке?",
    questionTextKz: "Орыс тілінде неше септік бар?",
    questionTextEn: "How many cases are there in Russian?",
    optionsRu: ["4", "5", "6", "7"],
    optionsKz: ["4", "5", "6", "7"],
    optionsEn: ["4", "5", "6", "7"],
    correctAnswer: 2,
    difficulty: "easy",
    topic: "Грамматика",
  },
  {
    subject: "reading_literacy",
    questionTextRu: "Какая часть речи обозначает действие предмета?",
    questionTextKz: "Сөз табының қайсысы заттың іс-әрекетін білдіреді?",
    questionTextEn: "Which part of speech denotes an action?",
    optionsRu: ["Существительное", "Глагол", "Прилагательное", "Наречие"],
    optionsKz: ["Зат есім", "Етістік", "Сын есім", "Үстеу"],
    optionsEn: ["Noun", "Verb", "Adjective", "Adverb"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Морфология",
  },
  {
    subject: "reading_literacy",
    questionTextRu: "Что такое фразеологизм?",
    questionTextKz: "Фразеологизм дегеніміз не?",
    questionTextEn: "What is a phraseological unit?",
    optionsRu: [
      "Новое слово",
      "Устойчивое выражение",
      "Иностранное слово",
      "Однокоренное слово",
    ],
    optionsKz: [
      "Жаңа сөз",
      "Тұрақты тіркес",
      "Шет тілден сөз",
      "Түбірлес сөз",
    ],
    optionsEn: [
      "A new word",
      "A fixed expression",
      "A foreign word",
      "A cognate word",
    ],
    correctAnswer: 1,
    difficulty: "medium",
    topic: "Фразеология",
  },
  {
    subject: "reading_literacy",
    questionTextRu: "Стиль речи научной статьи:",
    questionTextKz: "Ғылыми мақаланың сөйлеу стилі:",
    questionTextEn: "The speech style of a scientific article:",
    optionsRu: ["Разговорный", "Научный", "Художественный", "Публицистический"],
    optionsKz: ["Сөйлесу", "Ғылыми", "Көркем", "Публицистикалық"],
    optionsEn: ["Colloquial", "Scientific", "Literary", "Journalistic"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Стилистика",
  },
  {
    subject: "reading_literacy",
    questionTextRu: "Гипербола — это:",
    questionTextKz: "Гипербола — бұл:",
    questionTextEn: "Hyperbole is:",
    optionsRu: [
      "Преуменьшение",
      "Преувеличение",
      "Сравнение",
      "Олицетворение",
    ],
    optionsKz: [
      "Кемсіту",
      "Асыра сілтеу",
      "Салыстыру",
      "Кейіптеу",
    ],
    optionsEn: [
      "Understatement",
      "Exaggeration",
      "Comparison",
      "Personification",
    ],
    correctAnswer: 1,
    difficulty: "medium",
    topic: "Художественные средства",
  },
  {
    subject: "reading_literacy",
    questionTextRu: "Автор романа 'Путь Абая':",
    questionTextKz: "'Абай жолы' романының авторы:",
    questionTextEn: "The author of the novel 'The Path of Abai':",
    optionsRu: ["Абай Кунанбаев", "Мухтар Ауэзов", "Ильяс Жансугуров", "Сакен Сейфуллин"],
    optionsKz: ["Абай Құнанбаев", "Мұхтар Әуезов", "Ілияс Жансүгіров", "Сәкен Сейфуллин"],
    optionsEn: ["Abai Kunanbayev", "Mukhtar Auezov", "Ilyas Zhansugurov", "Saken Seifullin"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Литература",
  },
  {
    subject: "reading_literacy",
    questionTextRu: "Какой тип текста содержит аргументы за и против?",
    questionTextKz: "Қандай мәтін түрі жақтау және қарсы дәлелдерді қамтиды?",
    questionTextEn: "What type of text contains arguments for and against?",
    optionsRu: ["Описание", "Повествование", "Рассуждение", "Инструкция"],
    optionsKz: ["Сипаттау", "Баяндау", "Пайымдау", "Нұсқаулық"],
    optionsEn: ["Description", "Narration", "Argumentation", "Instruction"],
    correctAnswer: 2,
    difficulty: "medium",
    topic: "Типы текста",
  },
  {
    subject: "reading_literacy",
    questionTextRu: "Омонимы — это слова:",
    questionTextKz: "Омонимдер — бұл сөздер:",
    questionTextEn: "Homonyms are words that:",
    optionsRu: [
      "С противоположным значением",
      "Одинаковые по звучанию, разные по значению",
      "Близкие по значению",
      "С одним корнем",
    ],
    optionsKz: [
      "Қарама-қарсы мағыналы",
      "Дыбысталуы бірдей, мағынасы әр түрлі",
      "Мағынасы жақын",
      "Түбірі бір",
    ],
    optionsEn: [
      "With opposite meaning",
      "Same sound, different meaning",
      "Similar meaning",
      "Same root",
    ],
    correctAnswer: 1,
    difficulty: "medium",
    topic: "Лексика",
  },

  // HISTORY OF KAZAKHSTAN (20+ questions)
  {
    subject: "history_kz",
    questionTextRu: "Когда Казахстан обрел независимость?",
    questionTextKz: "Қазақстан тәуелсіздігін қашан алды?",
    questionTextEn: "When did Kazakhstan gain independence?",
    optionsRu: ["1990", "1991", "1992", "1993"],
    optionsKz: ["1990", "1991", "1992", "1993"],
    optionsEn: ["1990", "1991", "1992", "1993"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Независимость",
  },
  {
    subject: "history_kz",
    questionTextRu: "Столица Казахстана с 1997 года:",
    questionTextKz: "1997 жылдан бастап Қазақстанның астанасы:",
    questionTextEn: "The capital of Kazakhstan since 1997:",
    optionsRu: ["Алматы", "Астана", "Шымкент", "Караганда"],
    optionsKz: ["Алматы", "Астана", "Шымкент", "Қарағанды"],
    optionsEn: ["Almaty", "Astana", "Shymkent", "Karaganda"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Государственность",
  },
  {
    subject: "history_kz",
    questionTextRu: "Кто является основателем Казахского ханства?",
    questionTextKz: "Қазақ хандығының негізін қалаушы кім?",
    questionTextEn: "Who is the founder of the Kazakh Khanate?",
    optionsRu: [
      "Абылай хан",
      "Керей и Жанибек",
      "Тауке хан",
      "Касым хан",
    ],
    optionsKz: [
      "Абылай хан",
      "Керей мен Жәнібек",
      "Тәуке хан",
      "Қасым хан",
    ],
    optionsEn: [
      "Abylai Khan",
      "Kerey and Zhanibek",
      "Tauke Khan",
      "Kasym Khan",
    ],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Казахское ханство",
  },
  {
    subject: "history_kz",
    questionTextRu: "В каком году было образовано Казахское ханство?",
    questionTextKz: "Қазақ хандығы қай жылы құрылды?",
    questionTextEn: "In what year was the Kazakh Khanate formed?",
    optionsRu: ["1365", "1465", "1565", "1665"],
    optionsKz: ["1365", "1465", "1565", "1665"],
    optionsEn: ["1365", "1465", "1565", "1665"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Казахское ханство",
  },
  {
    subject: "history_kz",
    questionTextRu: "Сколько жузов было в казахском обществе?",
    questionTextKz: "Қазақ қоғамында неше жүз болды?",
    questionTextEn: "How many zhuzes were in Kazakh society?",
    optionsRu: ["2", "3", "4", "5"],
    optionsKz: ["2", "3", "4", "5"],
    optionsEn: ["2", "3", "4", "5"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Социальная структура",
  },
  {
    subject: "history_kz",
    questionTextRu: "Декабрьские события 1986 года произошли в:",
    questionTextKz: "1986 жылғы Желтоқсан оқиғалары болған қала:",
    questionTextEn: "The December 1986 events took place in:",
    optionsRu: ["Караганде", "Алма-Ате", "Семипалатинске", "Актобе"],
    optionsKz: ["Қарағандыда", "Алматыда", "Семейде", "Ақтөбеде"],
    optionsEn: ["Karaganda", "Alma-Ata", "Semipalatinsk", "Aktobe"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Советский период",
  },
  {
    subject: "history_kz",
    questionTextRu: "Великий казахский поэт и мыслитель XIX века:",
    questionTextKz: "XIX ғасырдағы ұлы қазақ ақыны және ойшылы:",
    questionTextEn: "The great Kazakh poet and thinker of the 19th century:",
    optionsRu: ["Абай Кунанбаев", "Шокан Валиханов", "Ибрай Алтынсарин", "Ахмет Байтурсынов"],
    optionsKz: ["Абай Құнанбаев", "Шоқан Уәлиханов", "Ыбырай Алтынсарин", "Ахмет Байтұрсынов"],
    optionsEn: ["Abai Kunanbayev", "Shokan Valikhanov", "Ibray Altynsarin", "Akhmet Baitursynov"],
    correctAnswer: 0,
    difficulty: "easy",
    topic: "Культура",
  },
  {
    subject: "history_kz",
    questionTextRu: "Семипалатинский ядерный полигон был закрыт в:",
    questionTextKz: "Семей ядролық полигоны жабылған жыл:",
    questionTextEn: "The Semipalatinsk nuclear test site was closed in:",
    optionsRu: ["1989", "1991", "1993", "1995"],
    optionsKz: ["1989", "1991", "1993", "1995"],
    optionsEn: ["1989", "1991", "1993", "1995"],
    correctAnswer: 1,
    difficulty: "medium",
    topic: "Независимость",
  },
  {
    subject: "history_kz",
    questionTextRu: "Движение 'Алаш' было создано в:",
    questionTextKz: "'Алаш' қозғалысы құрылған жыл:",
    questionTextEn: "The 'Alash' movement was created in:",
    optionsRu: ["1905", "1917", "1920", "1925"],
    optionsKz: ["1905", "1917", "1920", "1925"],
    optionsEn: ["1905", "1917", "1920", "1925"],
    correctAnswer: 1,
    difficulty: "medium",
    topic: "Национальное движение",
  },
  {
    subject: "history_kz",
    questionTextRu: "Голощекинская конфискация скота произошла в:",
    questionTextKz: "Голощекиннің мал тәркілеуі болған кезең:",
    questionTextEn: "Goloshchekin's cattle confiscation happened in:",
    optionsRu: ["1920-е годы", "1928-1932", "1935-1940", "1941-1945"],
    optionsKz: ["1920 жылдар", "1928-1932", "1935-1940", "1941-1945"],
    optionsEn: ["1920s", "1928-1932", "1935-1940", "1941-1945"],
    correctAnswer: 1,
    difficulty: "medium",
    topic: "Советский период",
  },
  {
    subject: "history_kz",
    questionTextRu: "Первый президент Республики Казахстан:",
    questionTextKz: "Қазақстан Республикасының тұңғыш Президенті:",
    questionTextEn: "The first President of the Republic of Kazakhstan:",
    optionsRu: ["Н. Назарбаев", "К. Токаев", "Д. Кунаев", "Н. Тлендиев"],
    optionsKz: ["Н. Назарбаев", "Қ. Тоқаев", "Д. Қонаев", "Н. Тілендиев"],
    optionsEn: ["N. Nazarbayev", "K. Tokayev", "D. Kunayev", "N. Tlendiyev"],
    correctAnswer: 0,
    difficulty: "easy",
    topic: "Независимость",
  },
  {
    subject: "history_kz",
    questionTextRu: "Национальная валюта Казахстана — тенге была введена в:",
    questionTextKz: "Қазақстанның ұлттық валютасы — теңге енгізілген жыл:",
    questionTextEn: "The national currency of Kazakhstan — tenge was introduced in:",
    optionsRu: ["1991", "1993", "1995", "1997"],
    optionsKz: ["1991", "1993", "1995", "1997"],
    optionsEn: ["1991", "1993", "1995", "1997"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Экономика",
  },
  {
    subject: "history_kz",
    questionTextRu: "Андроновская культура относится к эпохе:",
    questionTextKz: "Андронов мәдениеті дәуірге жатады:",
    questionTextEn: "The Andronovo culture belongs to the era of:",
    optionsRu: ["Каменный век", "Бронзовый век", "Железный век", "Средневековье"],
    optionsKz: ["Тас дәуірі", "Қола дәуірі", "Темір дәуірі", "Орта ғасыр"],
    optionsEn: ["Stone Age", "Bronze Age", "Iron Age", "Middle Ages"],
    correctAnswer: 1,
    difficulty: "medium",
    topic: "Древняя история",
  },
  {
    subject: "history_kz",
    questionTextRu: "Сакские племена населяли территорию Казахстана в:",
    questionTextKz: "Сақ тайпалары Қазақстан аумағында қоныстанған кезең:",
    questionTextEn: "Saka tribes inhabited Kazakhstan in:",
    optionsRu: ["III тыс. до н.э.", "I тыс. до н.э.", "I-V вв. н.э.", "VI-X вв."],
    optionsKz: ["б.з.д. III мыңжылдық", "б.з.д. I мыңжылдық", "б.з. I-V ғғ.", "VI-X ғғ."],
    optionsEn: ["3rd millennium BC", "1st millennium BC", "1st-5th century AD", "6th-10th century"],
    correctAnswer: 1,
    difficulty: "medium",
    topic: "Древняя история",
  },
  {
    subject: "history_kz",
    questionTextRu: "Тюркский каганат был основан в:",
    questionTextKz: "Түрік қағанаты құрылған жыл:",
    questionTextEn: "The Turkic Khaganate was founded in:",
    optionsRu: ["452 г.", "552 г.", "652 г.", "752 г."],
    optionsKz: ["452 ж.", "552 ж.", "652 ж.", "752 ж."],
    optionsEn: ["452 AD", "552 AD", "652 AD", "752 AD"],
    correctAnswer: 1,
    difficulty: "medium",
    topic: "Тюркский период",
  },
  {
    subject: "history_kz",
    questionTextRu: "Восстание Кенесары Касымова произошло в:",
    questionTextKz: "Кенесары Қасымов көтерілісі болған жылдар:",
    questionTextEn: "The revolt of Kenesary Kasymov took place in:",
    optionsRu: ["1825-1830", "1837-1847", "1850-1860", "1870-1880"],
    optionsKz: ["1825-1830", "1837-1847", "1850-1860", "1870-1880"],
    optionsEn: ["1825-1830", "1837-1847", "1850-1860", "1870-1880"],
    correctAnswer: 1,
    difficulty: "medium",
    topic: "Национально-освободительное движение",
  },
  {
    subject: "history_kz",
    questionTextRu: "Шокан Валиханов был первым казахским:",
    questionTextKz: "Шоқан Уәлиханов алғашқы қазақ:",
    questionTextEn: "Shokan Valikhanov was the first Kazakh:",
    optionsRu: ["Врачом", "Ученым", "Музыкантом", "Художником"],
    optionsKz: ["Дәрігер", "Ғалым", "Музыкант", "Суретші"],
    optionsEn: ["Doctor", "Scientist", "Musician", "Artist"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Культура",
  },
  {
    subject: "history_kz",
    questionTextRu: "Какой город был столицей Казахской ССР до 1997 года?",
    questionTextKz: "1997 жылға дейін Қазақ КСР-ның астанасы қай қала болды?",
    questionTextEn: "Which city was the capital of the Kazakh SSR before 1997?",
    optionsRu: ["Караганда", "Алма-Ата", "Шымкент", "Семипалатинск"],
    optionsKz: ["Қарағанды", "Алматы", "Шымкент", "Семей"],
    optionsEn: ["Karaganda", "Alma-Ata", "Shymkent", "Semipalatinsk"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Государственность",
  },
  {
    subject: "history_kz",
    questionTextRu: "Ибрай Алтынсарин известен как основатель:",
    questionTextKz: "Ыбырай Алтынсарин негізін қалаушы ретінде белгілі:",
    questionTextEn: "Ibray Altynsarin is known as the founder of:",
    optionsRu: ["Казахской музыки", "Казахского образования", "Казахской литературы", "Казахской медицины"],
    optionsKz: ["Қазақ музыкасы", "Қазақ білімі", "Қазақ әдебиеті", "Қазақ медицинасы"],
    optionsEn: ["Kazakh music", "Kazakh education", "Kazakh literature", "Kazakh medicine"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Культура",
  },
  {
    subject: "history_kz",
    questionTextRu: "Великий Шелковый путь проходил через:",
    questionTextKz: "Ұлы Жібек жолы өткен аймақ:",
    questionTextEn: "The Great Silk Road passed through:",
    optionsRu: ["Только Европу", "Только Китай", "Территорию Казахстана", "Только Индию"],
    optionsKz: ["Тек Еуропа", "Тек Қытай", "Қазақстан аумағы", "Тек Үндістан"],
    optionsEn: ["Only Europe", "Only China", "The territory of Kazakhstan", "Only India"],
    correctAnswer: 2,
    difficulty: "easy",
    topic: "Средневековье",
  },

  // MATHEMATICS (profile, 45+ questions - providing 20 representative ones)
  {
    subject: "math",
    questionTextRu: "Найдите производную функции f(x) = 3x² + 2x",
    questionTextKz: "f(x) = 3x² + 2x функциясының туындысын табыңыз",
    questionTextEn: "Find the derivative of f(x) = 3x² + 2x",
    optionsRu: ["6x + 2", "3x + 2", "6x² + 2", "3x² + 2"],
    optionsKz: ["6x + 2", "3x + 2", "6x² + 2", "3x² + 2"],
    optionsEn: ["6x + 2", "3x + 2", "6x² + 2", "3x² + 2"],
    correctAnswer: 0,
    difficulty: "medium",
    topic: "Производные",
  },
  {
    subject: "math",
    questionTextRu: "Решите уравнение: x² - 5x + 6 = 0",
    questionTextKz: "Теңдеуді шешіңіз: x² - 5x + 6 = 0",
    questionTextEn: "Solve: x² - 5x + 6 = 0",
    optionsRu: ["x = 1, x = 6", "x = 2, x = 3", "x = -2, x = -3", "x = 1, x = 5"],
    optionsKz: ["x = 1, x = 6", "x = 2, x = 3", "x = -2, x = -3", "x = 1, x = 5"],
    optionsEn: ["x = 1, x = 6", "x = 2, x = 3", "x = -2, x = -3", "x = 1, x = 5"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Квадратные уравнения",
  },
  {
    subject: "math",
    questionTextRu: "sin(30°) равен:",
    questionTextKz: "sin(30°) тең:",
    questionTextEn: "sin(30°) equals:",
    optionsRu: ["1/3", "1/2", "√2/2", "√3/2"],
    optionsKz: ["1/3", "1/2", "√2/2", "√3/2"],
    optionsEn: ["1/3", "1/2", "√2/2", "√3/2"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Тригонометрия",
  },
  {
    subject: "math",
    questionTextRu: "log₂(8) равен:",
    questionTextKz: "log₂(8) тең:",
    questionTextEn: "log₂(8) equals:",
    optionsRu: ["2", "3", "4", "8"],
    optionsKz: ["2", "3", "4", "8"],
    optionsEn: ["2", "3", "4", "8"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Логарифмы",
  },
  {
    subject: "math",
    questionTextRu: "Интеграл ∫2x dx равен:",
    questionTextKz: "∫2x dx интегралы тең:",
    questionTextEn: "The integral ∫2x dx equals:",
    optionsRu: ["x²", "x² + C", "2x² + C", "x + C"],
    optionsKz: ["x²", "x² + C", "2x² + C", "x + C"],
    optionsEn: ["x²", "x² + C", "2x² + C", "x + C"],
    correctAnswer: 1,
    difficulty: "medium",
    topic: "Интегралы",
  },
  {
    subject: "math",
    questionTextRu: "Сумма углов треугольника равна:",
    questionTextKz: "Үшбұрыш бұрыштарының қосындысы:",
    questionTextEn: "The sum of angles in a triangle is:",
    optionsRu: ["90°", "180°", "270°", "360°"],
    optionsKz: ["90°", "180°", "270°", "360°"],
    optionsEn: ["90°", "180°", "270°", "360°"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Геометрия",
  },
  {
    subject: "math",
    questionTextRu: "Формула дискриминанта квадратного уравнения:",
    questionTextKz: "Квадрат теңдеудің дискриминант формуласы:",
    questionTextEn: "The discriminant formula of a quadratic equation:",
    optionsRu: ["D = b² - 4ac", "D = b² + 4ac", "D = a² - 4bc", "D = 4ac - b²"],
    optionsKz: ["D = b² - 4ac", "D = b² + 4ac", "D = a² - 4bc", "D = 4ac - b²"],
    optionsEn: ["D = b² - 4ac", "D = b² + 4ac", "D = a² - 4bc", "D = 4ac - b²"],
    correctAnswer: 0,
    difficulty: "easy",
    topic: "Квадратные уравнения",
  },
  {
    subject: "math",
    questionTextRu: "Арифметическая прогрессия: 2, 5, 8, ... Найдите 10-й член:",
    questionTextKz: "Арифметикалық прогрессия: 2, 5, 8, ... 10-шы мүшесін табыңыз:",
    questionTextEn: "Arithmetic progression: 2, 5, 8, ... Find the 10th term:",
    optionsRu: ["26", "29", "32", "35"],
    optionsKz: ["26", "29", "32", "35"],
    optionsEn: ["26", "29", "32", "35"],
    correctAnswer: 1,
    difficulty: "medium",
    topic: "Прогрессии",
  },

  // PHYSICS (profile)
  {
    subject: "physics",
    questionTextRu: "Единица измерения силы в СИ:",
    questionTextKz: "ХЖ-дегі күш өлшем бірлігі:",
    questionTextEn: "The SI unit of force:",
    optionsRu: ["Джоуль", "Ньютон", "Ватт", "Паскаль"],
    optionsKz: ["Джоуль", "Ньютон", "Ватт", "Паскаль"],
    optionsEn: ["Joule", "Newton", "Watt", "Pascal"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Механика",
  },
  {
    subject: "physics",
    questionTextRu: "Формула второго закона Ньютона:",
    questionTextKz: "Ньютонның екінші заңының формуласы:",
    questionTextEn: "Newton's second law formula:",
    optionsRu: ["F = mv", "F = ma", "F = mg", "F = mgh"],
    optionsKz: ["F = mv", "F = ma", "F = mg", "F = mgh"],
    optionsEn: ["F = mv", "F = ma", "F = mg", "F = mgh"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Механика",
  },
  {
    subject: "physics",
    questionTextRu: "Скорость света в вакууме приблизительно равна:",
    questionTextKz: "Вакуумдағы жарық жылдамдығы шамамен:",
    questionTextEn: "The speed of light in vacuum is approximately:",
    optionsRu: ["3×10⁶ м/с", "3×10⁸ м/с", "3×10¹⁰ м/с", "3×10⁴ м/с"],
    optionsKz: ["3×10⁶ м/с", "3×10⁸ м/с", "3×10¹⁰ м/с", "3×10⁴ м/с"],
    optionsEn: ["3×10⁶ m/s", "3×10⁸ m/s", "3×10¹⁰ m/s", "3×10⁴ m/s"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Оптика",
  },
  {
    subject: "physics",
    questionTextRu: "Закон Ома для участка цепи:",
    questionTextKz: "Тізбек бөлігі үшін Ом заңы:",
    questionTextEn: "Ohm's law for a circuit section:",
    optionsRu: ["I = U/R", "I = UR", "I = R/U", "U = IR²"],
    optionsKz: ["I = U/R", "I = UR", "I = R/U", "U = IR²"],
    optionsEn: ["I = U/R", "I = UR", "I = R/U", "U = IR²"],
    correctAnswer: 0,
    difficulty: "easy",
    topic: "Электричество",
  },
  {
    subject: "physics",
    questionTextRu: "Ускорение свободного падения на Земле примерно равно:",
    questionTextKz: "Жердегі еркін түсу үдеуі шамамен тең:",
    questionTextEn: "The acceleration due to gravity on Earth is approximately:",
    optionsRu: ["5 м/с²", "9.8 м/с²", "15 м/с²", "20 м/с²"],
    optionsKz: ["5 м/с²", "9.8 м/с²", "15 м/с²", "20 м/с²"],
    optionsEn: ["5 m/s²", "9.8 m/s²", "15 m/s²", "20 m/s²"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Механика",
  },
  {
    subject: "physics",
    questionTextRu: "Кинетическая энергия тела вычисляется по формуле:",
    questionTextKz: "Дененің кинетикалық энергиясы формуламен есептеледі:",
    questionTextEn: "Kinetic energy is calculated by the formula:",
    optionsRu: ["E = mgh", "E = mv²/2", "E = mv", "E = Fs"],
    optionsKz: ["E = mgh", "E = mv²/2", "E = mv", "E = Fs"],
    optionsEn: ["E = mgh", "E = mv²/2", "E = mv", "E = Fs"],
    correctAnswer: 1,
    difficulty: "medium",
    topic: "Энергия",
  },

  // CHEMISTRY (profile)
  {
    subject: "chemistry",
    questionTextRu: "Химическая формула воды:",
    questionTextKz: "Судың химиялық формуласы:",
    questionTextEn: "The chemical formula of water:",
    optionsRu: ["H₂O", "CO₂", "NaCl", "H₂SO₄"],
    optionsKz: ["H₂O", "CO₂", "NaCl", "H₂SO₄"],
    optionsEn: ["H₂O", "CO₂", "NaCl", "H₂SO₄"],
    correctAnswer: 0,
    difficulty: "easy",
    topic: "Неорганическая химия",
  },
  {
    subject: "chemistry",
    questionTextRu: "Какой элемент имеет атомный номер 1?",
    questionTextKz: "Қай элементтің атом нөмірі 1?",
    questionTextEn: "Which element has atomic number 1?",
    optionsRu: ["Гелий", "Водород", "Литий", "Углерод"],
    optionsKz: ["Гелий", "Сутегі", "Литий", "Көміртегі"],
    optionsEn: ["Helium", "Hydrogen", "Lithium", "Carbon"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Периодическая таблица",
  },
  {
    subject: "chemistry",
    questionTextRu: "pH нейтрального раствора равен:",
    questionTextKz: "Бейтарап ерітіндінің pH мәні:",
    questionTextEn: "The pH of a neutral solution is:",
    optionsRu: ["0", "5", "7", "14"],
    optionsKz: ["0", "5", "7", "14"],
    optionsEn: ["0", "5", "7", "14"],
    correctAnswer: 2,
    difficulty: "easy",
    topic: "Растворы",
  },
  {
    subject: "chemistry",
    questionTextRu: "Число Авогадро приблизительно равно:",
    questionTextKz: "Авогадро саны шамамен тең:",
    questionTextEn: "Avogadro's number is approximately:",
    optionsRu: ["6.02×10²³", "3.14×10²³", "6.02×10²⁰", "9.8×10²³"],
    optionsKz: ["6.02×10²³", "3.14×10²³", "6.02×10²⁰", "9.8×10²³"],
    optionsEn: ["6.02×10²³", "3.14×10²³", "6.02×10²⁰", "9.8×10²³"],
    correctAnswer: 0,
    difficulty: "medium",
    topic: "Основы химии",
  },

  // BIOLOGY (profile)
  {
    subject: "biology",
    questionTextRu: "Клетка — основная единица:",
    questionTextKz: "Жасуша — негізгі бірлігі:",
    questionTextEn: "The cell is the basic unit of:",
    optionsRu: ["Энергии", "Жизни", "Химии", "Физики"],
    optionsKz: ["Энергия", "Тіршілік", "Химия", "Физика"],
    optionsEn: ["Energy", "Life", "Chemistry", "Physics"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Цитология",
  },
  {
    subject: "biology",
    questionTextRu: "ДНК расшифровывается как:",
    questionTextKz: "ДНҚ толық аты:",
    questionTextEn: "DNA stands for:",
    optionsRu: [
      "Динуклеиновая кислота",
      "Дезоксирибонуклеиновая кислота",
      "Дирибонуклеиновая кислота",
      "Деоксинуклеиновая кислота",
    ],
    optionsKz: [
      "Динуклеин қышқылы",
      "Дезоксирибонуклеин қышқылы",
      "Дирибонуклеин қышқылы",
      "Деоксинуклеин қышқылы",
    ],
    optionsEn: [
      "Dinucleic acid",
      "Deoxyribonucleic acid",
      "Diribonucleic acid",
      "Deoxynucleic acid",
    ],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Генетика",
  },
  {
    subject: "biology",
    questionTextRu: "Фотосинтез происходит в:",
    questionTextKz: "Фотосинтез жүреді:",
    questionTextEn: "Photosynthesis occurs in:",
    optionsRu: ["Митохондриях", "Хлоропластах", "Рибосомах", "Лизосомах"],
    optionsKz: ["Митохондрияда", "Хлоропластта", "Рибосомада", "Лизосомада"],
    optionsEn: ["Mitochondria", "Chloroplasts", "Ribosomes", "Lysosomes"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Ботаника",
  },

  // GEOGRAPHY
  {
    subject: "geography",
    questionTextRu: "Самое большое озеро в мире:",
    questionTextKz: "Әлемдегі ең үлкен көл:",
    questionTextEn: "The largest lake in the world:",
    optionsRu: ["Байкал", "Каспийское море", "Виктория", "Верхнее"],
    optionsKz: ["Байкал", "Каспий теңізі", "Виктория", "Жоғарғы"],
    optionsEn: ["Baikal", "Caspian Sea", "Victoria", "Superior"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Гидрография",
  },
  {
    subject: "geography",
    questionTextRu: "Площадь Казахстана составляет примерно:",
    questionTextKz: "Қазақстанның аумағы шамамен:",
    questionTextEn: "The area of Kazakhstan is approximately:",
    optionsRu: ["1.7 млн км²", "2.7 млн км²", "3.7 млн км²", "4.7 млн км²"],
    optionsKz: ["1.7 млн км²", "2.7 млн км²", "3.7 млн км²", "4.7 млн км²"],
    optionsEn: ["1.7M km²", "2.7M km²", "3.7M km²", "4.7M km²"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "География Казахстана",
  },

  // ENGLISH
  {
    subject: "english",
    questionTextRu: "Выберите правильную форму: She ___ to school every day.",
    questionTextKz: "Дұрыс формасын таңдаңыз: She ___ to school every day.",
    questionTextEn: "Choose the correct form: She ___ to school every day.",
    optionsRu: ["go", "goes", "going", "gone"],
    optionsKz: ["go", "goes", "going", "gone"],
    optionsEn: ["go", "goes", "going", "gone"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Present Simple",
  },
  {
    subject: "english",
    questionTextRu: "Past Simple от 'go':",
    questionTextKz: "'go' етістігінің Past Simple формасы:",
    questionTextEn: "Past Simple of 'go':",
    optionsRu: ["goed", "went", "gone", "goes"],
    optionsKz: ["goed", "went", "gone", "goes"],
    optionsEn: ["goed", "went", "gone", "goes"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Past Simple",
  },

  // INFORMATICS
  {
    subject: "informatics",
    questionTextRu: "1 килобайт равен:",
    questionTextKz: "1 килобайт тең:",
    questionTextEn: "1 kilobyte equals:",
    optionsRu: ["100 байт", "512 байт", "1024 байт", "2048 байт"],
    optionsKz: ["100 байт", "512 байт", "1024 байт", "2048 байт"],
    optionsEn: ["100 bytes", "512 bytes", "1024 bytes", "2048 bytes"],
    correctAnswer: 2,
    difficulty: "easy",
    topic: "Единицы информации",
  },
  {
    subject: "informatics",
    questionTextRu: "Двоичная система счисления основана на числе:",
    questionTextKz: "Екілік санау жүйесі санға негізделген:",
    questionTextEn: "The binary number system is based on:",
    optionsRu: ["2", "8", "10", "16"],
    optionsKz: ["2", "8", "10", "16"],
    optionsEn: ["2", "8", "10", "16"],
    correctAnswer: 0,
    difficulty: "easy",
    topic: "Системы счисления",
  },

  // WORLD HISTORY
  {
    subject: "world_history",
    questionTextRu: "Вторая мировая война закончилась в:",
    questionTextKz: "Екінші дүниежүзілік соғыс аяқталған жыл:",
    questionTextEn: "World War II ended in:",
    optionsRu: ["1943", "1944", "1945", "1946"],
    optionsKz: ["1943", "1944", "1945", "1946"],
    optionsEn: ["1943", "1944", "1945", "1946"],
    correctAnswer: 2,
    difficulty: "easy",
    topic: "XX век",
  },
  {
    subject: "world_history",
    questionTextRu: "Французская революция началась в:",
    questionTextKz: "Француз революциясы басталған жыл:",
    questionTextEn: "The French Revolution began in:",
    optionsRu: ["1769", "1779", "1789", "1799"],
    optionsKz: ["1769", "1779", "1789", "1799"],
    optionsEn: ["1769", "1779", "1789", "1799"],
    correctAnswer: 2,
    difficulty: "easy",
    topic: "Новое время",
  },

  // LITERATURE
  {
    subject: "literature",
    questionTextRu: "Автор 'Войны и мира':",
    questionTextKz: "'Соғыс және бейбітшілік' авторы:",
    questionTextEn: "The author of 'War and Peace':",
    optionsRu: ["Достоевский", "Толстой", "Чехов", "Пушкин"],
    optionsKz: ["Достоевский", "Толстой", "Чехов", "Пушкин"],
    optionsEn: ["Dostoevsky", "Tolstoy", "Chekhov", "Pushkin"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Русская литература",
  },
  {
    subject: "literature",
    questionTextRu: "Кто написал 'Слова назидания'?",
    questionTextKz: "'Қара сөз' кімнің шығармасы?",
    questionTextEn: "Who wrote 'Words of Edification'?",
    optionsRu: ["Мухтар Ауэзов", "Абай Кунанбаев", "Жамбыл Жабаев", "Магжан Жумабаев"],
    optionsKz: ["Мұхтар Әуезов", "Абай Құнанбаев", "Жамбыл Жабаев", "Мағжан Жұмабаев"],
    optionsEn: ["Mukhtar Auezov", "Abai Kunanbayev", "Zhambyl Zhabayev", "Magzhan Zhumabayev"],
    correctAnswer: 1,
    difficulty: "easy",
    topic: "Казахская литература",
  },
];
