export enum AuditAction {
  USER_BANNED = "USER_BANNED",
  USER_UNBANNED = "USER_UNBANNED",
  USER_DELETED = "USER_DELETED",
  USER_RESTORED = "USER_RESTORED",
  USER_ADMIN_GRANTED = "USER_ADMIN_GRANTED",
  USER_ADMIN_REVOKED = "USER_ADMIN_REVOKED",
  USER_EMAIL_VERIFIED = "USER_EMAIL_VERIFIED",
  QUESTION_CREATED = "QUESTION_CREATED",
  QUESTION_UPDATED = "QUESTION_UPDATED",
  QUESTION_DELETED = "QUESTION_DELETED",
  UNIVERSITY_CREATED = "UNIVERSITY_CREATED",
  UNIVERSITY_UPDATED = "UNIVERSITY_UPDATED",
  UNIVERSITY_DELETED = "UNIVERSITY_DELETED",
}

export enum AuditEntityType {
  USER = "USER",
  QUESTION = "QUESTION",
  UNIVERSITY = "UNIVERSITY",
  SYSTEM = "SYSTEM",
}
